services:
  cassandra:
    image: "cassandra:latest"
    container_name: falcontodo-db
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
  web:
    container_name: falcontodo-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /www
volumes:
  cassandra_data:
